name = "honk-compendium"
main = "src/index.ts"
compatibility_date = "2024-12-12"
compatibility_flags = ["nodejs_compat"]

route = ""
account_id = "account-id"

[vars]
DATABASE_URL = "your-database-url"

